version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000


# http://localhost:8080
# myadminsecretkey

# https://assuring-kodiak-14.hasura.app/v1/graphql
# x-hasura-admin-secret - tDOAa0RBqtJii9vU5kGR35S1AnCBHLaw6Kri9Huc8sgvPoL8dznwrYgdZXsrEtCm